local type = "camp_crafting"

Workbench[type] = {

    main_header = "Craft Table",
    main_subheader = "Craft Camp Items",
    categories = {
        [1] = {
            type = "craft",
            header = "Tents",
            subheader = "Tents Items",
            icon = "sirevlc_tent",
            anim = {"amb_work@world_human_hammer@table@male_a@trans", "base_trans_base"},
            recipe = {
                {label = "Trader Tent Small", description = "Requires: 50x Wood, 35x Iron, 25x Copper, 150x Nails, 15x Cloth", icon="sirevlc_tent", craft = {{"tent_trader01", 1}}, need = {{"wood", 50}, {"iron", 35}, {"copper", 25}, {"nails", 150}, {"cloth", 15}}, worktime = 5},
                {label = "Trader Tent Medium", description = "Requires: 50x Wood, 35x Iron, 25x Copper, 150x Nails, 15x Cloth", icon="sirevlc_tent", craft = {{"tent_trader02", 1}}, need = {{"wood", 50}, {"iron", 35}, {"copper", 25}, {"nails", 150}, {"cloth", 15}}, worktime = 5},
                {label = "Trader Tent Large", description = "Requires: 50x Wood, 35x Iron, 25x Copper, 150x Nails, 15x Cloth", icon="sirevlc_tent", craft = {{"tent_trader03", 1}}, need = {{"wood", 50}, {"iron", 35}, {"copper", 25}, {"nails", 150}, {"cloth", 15}}, worktime = 5},
                {label = "Trader Tent Extra Large", description = "Requires: 50x Wood, 35x Iron, 25x Copper, 150x Nails, 15x Cloth", icon="sirevlc_tent", craft = {{"tent_trader04", 1}}, need = {{"wood", 50}, {"iron", 35}, {"copper", 25}, {"nails", 150}, {"cloth", 15}}, worktime = 5},
                {label = "Trader Tent Deluxe", description = "Requires: 50x Wood, 35x Iron, 25x Copper, 150x Nails, 15x Cloth", icon="sirevlc_tent", craft = {{"tent_trader05", 1}}, need = {{"wood", 50}, {"iron", 35}, {"copper", 25}, {"nails", 150}, {"cloth", 15}}, worktime = 5},
                {label = "Trader Tent Premium", description = "Requires: 50x Wood, 35x Iron, 25x Copper, 150x Nails, 15x Cloth", icon="sirevlc_tent", craft = {{"tent_trader06", 1}}, need = {{"wood", 50}, {"iron", 35}, {"copper", 25}, {"nails", 150}, {"cloth", 15}}, worktime = 5},
                {label = "Trader Tent Ultimate", description = "Requires: 50x Wood, 35x Iron, 25x Copper, 150x Nails, 15x Cloth", icon="sirevlc_tent", craft = {{"tent_trader07", 1}}, need = {{"wood", 50}, {"iron", 35}, {"copper", 25}, {"nails", 150}, {"cloth", 15}}, worktime = 5},
                {label = "Bounty Hunter Tent Small", description = "Requires: 50x Wood, 35x Iron, 25x Copper, 150x Nails, 15x Cloth", icon="sirevlc_tent", craft = {{"tent_bounty01", 1}}, need = {{"wood", 50}, {"iron", 35}, {"copper", 25}, {"nails", 150}, {"cloth", 15}}, worktime = 5},
                {label = "Bounty Hunter Tent Medium", description = "Requires: 50x Wood, 35x Iron, 25x Copper, 150x Nails, 15x Cloth", icon="sirevlc_tent", craft = {{"tent_bounty02", 1}}, need = {{"wood", 50}, {"iron", 35}, {"copper", 25}, {"nails", 150}, {"cloth", 15}}, worktime = 5},
                {label = "Bounty Hunter Tent Large", description = "Requires: 50x Wood, 35x Iron, 25x Copper, 150x Nails, 15x Cloth", icon="sirevlc_tent", craft = {{"tent_bounty03", 1}}, need = {{"wood", 50}, {"iron", 35}, {"copper", 25}, {"nails", 150}, {"cloth", 15}}, worktime = 5},
                {label = "Bounty Hunter Tent Extra Large", description = "Requires: 50x Wood, 35x Iron, 25x Copper, 150x Nails, 15x Cloth", icon="sirevlc_tent", craft = {{"tent_bounty04", 1}}, need = {{"wood", 50}, {"iron", 35}, {"copper", 25}, {"nails", 150}, {"cloth", 15}}, worktime = 5},
                {label = "Bounty Hunter Tent Deluxe", description = "Requires: 50x Wood, 35x Iron, 25x Copper, 150x Nails, 15x Cloth", icon="sirevlc_tent", craft = {{"tent_bounty05", 1}}, need = {{"wood", 50}, {"iron", 35}, {"copper", 25}, {"nails", 150}, {"cloth", 15}}, worktime = 5},
                {label = "Bounty Hunter Tent Premium", description = "Requires: 50x Wood, 35x Iron, 25x Copper, 150x Nails, 15x Cloth", icon="sirevlc_tent", craft = {{"tent_bounty06", 1}}, need = {{"wood", 50}, {"iron", 35}, {"copper", 25}, {"nails", 150}, {"cloth", 15}}, worktime = 5},
                {label = "Bounty Hunter Tent Ultimate", description = "Requires: 50x Wood, 35x Iron, 25x Copper, 150x Nails, 15x Cloth", icon="sirevlc_tent", craft = {{"tent_bounty07", 1}}, need = {{"wood", 50}, {"iron", 35}, {"copper", 25}, {"nails", 150}, {"cloth", 15}}, worktime = 5},
                {label = "Collector Tent Small", description = "Requires: 50x Wood, 35x Iron, 25x Copper, 150x Nails, 15x Cloth", icon="sirevlc_tent", craft = {{"tent_collector01", 1}}, need = {{"wood", 50}, {"iron", 35}, {"copper", 25}, {"nails", 150}, {"cloth", 15}}, worktime = 5},
                {label = "Collector Tent Medium", description = "Requires: 50x Wood, 35x Iron, 25x Copper, 150x Nails, 15x Cloth", icon="sirevlc_tent", craft = {{"tent_collector02", 1}}, need = {{"wood", 50}, {"iron", 35}, {"copper", 25}, {"nails", 150}, {"cloth", 15}}, worktime = 5},
                {label = "Collector Tent Large", description = "Requires: 50x Wood, 35x Iron, 25x Copper, 150x Nails, 15x Cloth", icon="sirevlc_tent", craft = {{"tent_collector03", 1}}, need = {{"wood", 50}, {"iron", 35}, {"copper", 25}, {"nails", 150}, {"cloth", 15}}, worktime = 5},
                {label = "Collector Tent Extra Large", description = "Requires: 50x Wood, 35x Iron, 25x Copper, 150x Nails, 15x Cloth", icon="sirevlc_tent", craft = {{"tent_collector04", 1}}, need = {{"wood", 50}, {"iron", 35}, {"copper", 25}, {"nails", 150}, {"cloth", 15}}, worktime = 5},
                {label = "Collector Tent Deluxe", description = "Requires: 50x Wood, 35x Iron, 25x Copper, 150x Nails, 15x Cloth", icon="sirevlc_tent", craft = {{"tent_collector05", 1}}, need = {{"wood", 50}, {"iron", 35}, {"copper", 25}, {"nails", 150}, {"cloth", 15}}, worktime = 5},
                {label = "Collector Tent Premium", description = "Requires: 50x Wood, 35x Iron, 25x Copper, 150x Nails, 15x Cloth", icon="sirevlc_tent", craft = {{"tent_collector06", 1}}, need = {{"wood", 50}, {"iron", 35}, {"copper", 25}, {"nails", 150}, {"cloth", 15}}, worktime = 5},
                {label = "Collector Tent Ultimate", description = "Requires: 50x Wood, 35x Iron, 25x Copper, 150x Nails, 15x Cloth", icon="sirevlc_tent", craft = {{"tent_collector07", 1}}, need = {{"wood", 50}, {"iron", 35}, {"copper", 25}, {"nails", 150}, {"cloth", 15}}, worktime = 5},
                {label = "Savage A-Frame Tent", description = "Requires: 50x Wood, 35x Iron, 25x Copper, 150x Nails, 15x Cloth", icon="sirevlc_tent", craft = {{"tent_savage01", 1}}, need = {{"wood", 50}, {"iron", 35}, {"copper", 25}, {"nails", 150}, {"cloth", 15}}, worktime = 5},
                {label = "Savage Covered Lean-to", description = "Requires: 50x Wood, 35x Iron, 25x Copper, 150x Nails, 15x Cloth", icon="sirevlc_tent", craft = {{"tent_savage02", 1}}, need = {{"wood", 50}, {"iron", 35}, {"copper", 25}, {"nails", 150}, {"cloth", 15}}, worktime = 5},
                {label = "Savage Covered Tent", description = "Requires: 50x Wood, 35x Iron, 25x Copper, 150x Nails, 15x Cloth", icon="sirevlc_tent", craft = {{"tent_savage03", 1}}, need = {{"wood", 50}, {"iron", 35}, {"copper", 25}, {"nails", 150}, {"cloth", 15}}, worktime = 5},
                {label = "Savage Open Lean-to", description = "Requires: 50x Wood, 35x Iron, 25x Copper, 150x Nails, 15x Cloth", icon="sirevlc_tent", craft = {{"tent_savage04", 1}}, need = {{"wood", 50}, {"iron", 35}, {"copper", 25}, {"nails", 150}, {"cloth", 15}}, worktime = 5},
                {label = "Savage Simple Lean-to", description = "Requires: 50x Wood, 35x Iron, 25x Copper, 150x Nails, 15x Cloth", icon="sirevlc_tent", craft = {{"tent_savage05", 1}}, need = {{"wood", 50}, {"iron", 35}, {"copper", 25}, {"nails", 150}, {"cloth", 15}}, worktime = 5},
                {label = "Savage Tall Lean-to", description = "Requires: 50x Wood, 35x Iron, 25x Copper, 150x Nails, 15x Cloth", icon="sirevlc_tent", craft = {{"tent_savage06", 1}}, need = {{"wood", 50}, {"iron", 35}, {"copper", 25}, {"nails", 150}, {"cloth", 15}}, worktime = 5},
                {label = "Military A-Frame Tent", description = "Requires: 50x Wood, 35x Iron, 25x Copper, 150x Nails, 15x Cloth", icon="sirevlc_tent", craft = {{"tent_military01", 1}}, need = {{"wood", 50}, {"iron", 35}, {"copper", 25}, {"nails", 150}, {"cloth", 15}}, worktime = 5},
                {label = "Military Covered Lean-to", description = "Requires: 50x Wood, 35x Iron, 25x Copper, 150x Nails, 15x Cloth", icon="sirevlc_tent", craft = {{"tent_military02", 1}}, need = {{"wood", 50}, {"iron", 35}, {"copper", 25}, {"nails", 150}, {"cloth", 15}}, worktime = 5},
                {label = "Military Covered Tent", description = "Requires: 50x Wood, 35x Iron, 25x Copper, 150x Nails, 15x Cloth", icon="sirevlc_tent", craft = {{"tent_military03", 1}}, need = {{"wood", 50}, {"iron", 35}, {"copper", 25}, {"nails", 150}, {"cloth", 15}}, worktime = 5},
                {label = "Military Open Lean-to", description = "Requires: 50x Wood, 35x Iron, 25x Copper, 150x Nails, 15x Cloth", icon="sirevlc_tent", craft = {{"tent_military04", 1}}, need = {{"wood", 50}, {"iron", 35}, {"copper", 25}, {"nails", 150}, {"cloth", 15}}, worktime = 5},
                {label = "Military Simple Bedroll", description = "Requires: 50x Wood, 35x Iron, 25x Copper, 150x Nails, 15x Cloth", icon="sirevlc_tent", craft = {{"tent_military05", 1}}, need = {{"wood", 50}, {"iron", 35}, {"copper", 25}, {"nails", 150}, {"cloth", 15}}, worktime = 5},
                {label = "Military Simple Lean-to", description = "Requires: 50x Wood, 35x Iron, 25x Copper, 150x Nails, 15x Cloth", icon="sirevlc_tent", craft = {{"tent_military06", 1}}, need = {{"wood", 50}, {"iron", 35}, {"copper", 25}, {"nails", 150}, {"cloth", 15}}, worktime = 5},
                {label = "Military Tall Lean-to", description = "Requires: 50x Wood, 35x Iron, 25x Copper, 150x Nails, 15x Cloth", icon="sirevlc_tent", craft = {{"tent_military07", 1}}, need = {{"wood", 50}, {"iron", 35}, {"copper", 25}, {"nails", 150}, {"cloth", 15}}, worktime = 5},
                {label = "Hobo A-Frame Tent", description = "Requires: 50x Wood, 35x Iron, 25x Copper, 150x Nails, 15x Cloth", icon="sirevlc_tent", craft = {{"tent_hobo01", 1}}, need = {{"wood", 50}, {"iron", 35}, {"copper", 25}, {"nails", 150}, {"cloth", 15}}, worktime = 5},
                {label = "Hobo Covered Lean-to", description = "Requires: 50x Wood, 35x Iron, 25x Copper, 150x Nails, 15x Cloth", icon="sirevlc_tent", craft = {{"tent_hobo02", 1}}, need = {{"wood", 50}, {"iron", 35}, {"copper", 25}, {"nails", 150}, {"cloth", 15}}, worktime = 5},
                {label = "Hobo Covered Tent", description = "Requires: 50x Wood, 35x Iron, 25x Copper, 150x Nails, 15x Cloth", icon="sirevlc_tent", craft = {{"tent_hobo03", 1}}, need = {{"wood", 50}, {"iron", 35}, {"copper", 25}, {"nails", 150}, {"cloth", 15}}, worktime = 5},
                {label = "Hobo Open Lean-to", description = "Requires: 50x Wood, 35x Iron, 25x Copper, 150x Nails, 15x Cloth", icon="sirevlc_tent", craft = {{"tent_hobo04", 1}}, need = {{"wood", 50}, {"iron", 35}, {"copper", 25}, {"nails", 150}, {"cloth", 15}}, worktime = 5},
                {label = "Hobo Simple Bedroll", description = "Requires: 50x Wood, 35x Iron, 25x Copper, 150x Nails, 15x Cloth", icon="sirevlc_tent", craft = {{"tent_hobo05", 1}}, need = {{"wood", 50}, {"iron", 35}, {"copper", 25}, {"nails", 150}, {"cloth", 15}}, worktime = 5},
                {label = "Hobo Simple Lean-to", description = "Requires: 50x Wood, 35x Iron, 25x Copper, 150x Nails, 15x Cloth", icon="sirevlc_tent", craft = {{"tent_hobo06", 1}}, need = {{"wood", 50}, {"iron", 35}, {"copper", 25}, {"nails", 150}, {"cloth", 15}}, worktime = 5},
                {label = "Hobo Tall Lean-to", description = "Requires: 50x Wood, 35x Iron, 25x Copper, 150x Nails, 15x Cloth", icon="sirevlc_tent", craft = {{"tent_hobo07", 1}}, need = {{"wood", 50}, {"iron", 35}, {"copper", 25}, {"nails", 150}, {"cloth", 15}}, worktime = 5},
                {label = "Culture A-Frame Tent", description = "Requires: 50x Wood, 35x Iron, 25x Copper, 150x Nails, 15x Cloth", icon="sirevlc_tent", craft = {{"tent_culture01", 1}}, need = {{"wood", 50}, {"iron", 35}, {"copper", 25}, {"nails", 150}, {"cloth", 15}}, worktime = 5},
                {label = "Culture Covered Lean-to", description = "Requires: 50x Wood, 35x Iron, 25x Copper, 150x Nails, 15x Cloth", icon="sirevlc_tent", craft = {{"tent_culture02", 1}}, need = {{"wood", 50}, {"iron", 35}, {"copper", 25}, {"nails", 150}, {"cloth", 15}}, worktime = 5},
                {label = "Culture Covered Tent", description = "Requires: 50x Wood, 35x Iron, 25x Copper, 150x Nails, 15x Cloth", icon="sirevlc_tent", craft = {{"tent_culture03", 1}}, need = {{"wood", 50}, {"iron", 35}, {"copper", 25}, {"nails", 150}, {"cloth", 15}}, worktime = 5},
                {label = "Culture Open Lean-to", description = "Requires: 50x Wood, 35x Iron, 25x Copper, 150x Nails, 15x Cloth", icon="sirevlc_tent", craft = {{"tent_culture04", 1}}, need = {{"wood", 50}, {"iron", 35}, {"copper", 25}, {"nails", 150}, {"cloth", 15}}, worktime = 5},
                {label = "Culture Simple Bedroll", description = "Requires: 50x Wood, 35x Iron, 25x Copper, 150x Nails, 15x Cloth", icon= "sirevlc_tent", craft = {{"tent_culture05", 1}}, need = {{"wood", 50}, {"iron", 35}, {"copper", 25}, {"nails", 150}, {"cloth", 15}}, worktime = 5},
                {label = "Culture Simple Lean-to", description = "Requires: 50x Wood, 35x Iron, 25x Copper, 150x Nails, 15x Cloth", icon= "sirevlc_tent", craft = {{"tent_culture06", 1}}, need = {{"wood", 50}, {"iron", 35}, {"copper", 25}, {"nails", 150}, {"cloth", 15}}, worktime = 5},
                {label = "Culture Tall Lean-to", description = "Requires: 50x Wood, 35x Iron, 25x Copper, 150x Nails, 15x Cloth", icon= "sirevlc_tent", craft = {{"tent_culture07", 1}}, need = {{"wood", 50}, {"iron", 35}, {"copper", 25}, {"nails", 150}, {"cloth", 15}}, worktime = 5},
            }
        },
        [2] = {
            type = "craft",
            header = "Tables",
            subheader = "Tables Items",
            icon = "sirevlc_wagons_propsets",
            anim = {"amb_work@world_human_hammer@table@male_a@trans", "base_trans_base"},
            recipe = {
                {label = "Simple Table", description = "Requires: 15x Wood, 5x Iron, 5x Copper, 35x Nails", icon="sirevlc_wagons_propsets", craft = {{"tablesimple", 1}}, need = {{"wood", 15}, {"iron", 5}, {"copper", 5}, {"nails", 35}}, worktime = 5},
                {label = "Culture Table", description = "Requires: 15x Wood, 5x Iron, 5x Copper, 35x Nails", icon="sirevlc_wagons_propsets", craft = {{"tableculture", 1}}, need = {{"wood", 15}, {"iron", 5}, {"copper", 5}, {"nails", 35}}, worktime = 5},
                {label = "Collector Table", description = "Requires: 15x Wood, 5x Iron, 5x Copper, 35x Nails", icon="sirevlc_wagons_propsets", craft = {{"tablecolector", 1}}, need = {{"wood", 15}, {"iron", 5}, {"copper", 5}, {"nails", 35}}, worktime = 5},
                {label = "Bounty Hunter Table", description = "Requires: 15x Wood, 5x Iron, 5x Copper, 35x Nails", icon="sirevlc_wagons_propsets", craft = {{"tablebounty", 1}}, need = {{"wood", 15}, {"iron", 5}, {"copper", 5}, {"nails", 35}}, worktime = 5},
                {label = "Trader Table", description = "Requires: 15x Wood, 5x Iron, 5x Copper, 35x Nails", icon="sirevlc_wagons_propsets", craft = {{"tabletrader", 1}}, need = {{"wood", 15}, {"iron", 5}, {"copper", 5}, {"nails", 35}}, worktime = 5},
                {label = "Hobo Table", description = "Requires: 15x Wood, 5x Iron, 5x Copper, 35x Nails", icon="sirevlc_wagons_propsets", craft = {{"tablehobo", 1}}, need = {{"wood", 15}, {"iron", 5}, {"copper", 5}, {"nails", 35}}, worktime = 5},
                {label = "Military Table", description = "Requires: 15x Wood, 5x Iron, 5x Copper, 35x Nails", icon="sirevlc_wagons_propsets", craft = {{"tablemilitary", 1}}, need = {{"wood", 15}, {"iron", 5}, {"copper", 5}, {"nails", 35}}, worktime = 5},
                {label = "Savage Table", description = "Requires: 15x Wood, 5x Iron, 5x Copper, 35x Nails", icon="sirevlc_wagons_propsets", craft = {{"tablesavage", 1}}, need = {{"wood", 15}, {"iron", 5}, {"copper", 5}, {"nails", 35}}, worktime = 5},
                {label = "Food Table", description = "Requires: 15x Wood, 5x Iron, 5x Copper, 35x Nails", icon="sirevlc_wagons_propsets", craft = {{"tablefood", 1}}, need = {{"wood", 15}, {"iron", 5}, {"copper", 5}, {"nails", 35}}, worktime = 5},
                {label = "Small Table", description = "Requires: 15x Wood, 5x Iron, 5x Copper, 35x Nails", icon="sirevlc_wagons_propsets", craft = {{"smalltable01", 1}}, need = {{"wood", 15}, {"iron", 5}, {"copper", 5}, {"nails", 35}}, worktime = 5},
                {label = "Poker Table", description = "Requires: 15x Wood, 5x Iron, 5x Copper, 35x Nails", icon="sirevlc_wagons_propsets", craft = {{"pokertable", 1}}, need = {{"wood", 15}, {"iron", 5}, {"copper", 5}, {"nails", 35}}, worktime = 5},
                {label = "Butcher Table", description = "Requires: 15x Wood, 5x Iron, 5x Copper, 35x Nails", icon="sirevlc_wagons_propsets", craft = {{"butchertable", 1}}, need = {{"wood", 15}, {"iron", 5}, {"copper", 5}, {"nails", 35}}, worktime = 5},
            }
        },
        [3] = {
            type = "craft",
            header = "Decor",
            subheader = "Camp Decor!",
            icon = "sirevlc_rug",
            anim = {"amb_work@world_human_hammer@table@male_a@trans", "base_trans_base"},
            recipe = {
                {label = "Merchant Stand", description = "Requires: 15x Wood, 5x Iron, 5x Copper, 35x Nails", icon="sirevlc_rug", craft = {{"merchantstand", 1}}, need = {{"wood", 15}, {"iron", 5}, {"copper", 5}, {"nails", 35}}, worktime = 5},
                {label = "Bath", description = "Requires: 15x Wood, 5x Iron, 5x Copper, 35x Nails", icon="sirevlc_rug", craft = {{"bath", 1}}, need = {{"wood", 15}, {"iron", 5}, {"copper", 5}, {"nails", 35}}, worktime = 5},
                {label = "Laundry", description = "Requires: 15x Wood, 5x Iron, 5x Copper, 35x Nails", icon="sirevlc_rug", craft = {{"laundry", 1}}, need = {{"wood", 15}, {"iron", 5}, {"copper", 5}, {"nails", 35}}, worktime = 5},
                {label = "Explorer Herbs", description = "Requires: 15x Wood, 5x Iron, 5x Copper, 35x Nails", icon="sirevlc_rug", craft = {{"exploreherb", 1}}, need = {{"wood", 15}, {"iron", 5}, {"copper", 5}, {"nails", 35}}, worktime = 5},
                {label = "Gold Digger Kit", description = "Requires: 15x Wood, 5x Iron, 5x Copper, 35x Nails", icon="sirevlc_rug", craft = {{"golddigger", 1}}, need = {{"wood", 15}, {"iron", 5}, {"copper", 5}, {"nails", 35}}, worktime = 5},
                {label = "Pelt Station", description = "Requires: 15x Wood, 5x Iron, 5x Copper, 35x Nails", icon="sirevlc_rug", craft = {{"pelt", 1}}, need = {{"wood", 15}, {"iron", 5}, {"copper", 5}, {"nails", 35}}, worktime = 5},
                {label = "Cooking Station", description = "Requires: 15x Wood, 5x Iron, 5x Copper, 35x Nails", icon="sirevlc_rug", craft = {{"cookstation01", 1}}, need = {{"wood", 15}, {"iron", 5}, {"copper", 5}, {"nails", 35}}, worktime = 5},
                {label = "Water Barrel", description = "Requires: 15x Wood, 5x Iron, 5x Copper, 35x Nails", icon="sirevlc_rug", craft = {{"waterbarrel", 1}}, need = {{"wood", 15}, {"iron", 5}, {"copper", 5}, {"nails", 35}}, worktime = 5},
                {label = "Horse Enclosure Small", description = "Requires: 15x Wood, 5x Iron, 5x Copper, 35x Nails", icon="horse_rear_up", craft = {{"horseenclosure01", 1}}, need = {{"wood", 15}, {"iron", 5}, {"copper", 5}, {"nails", 35}}, worktime = 5},
                {label = "Horse Enclosure Medium", description = "Requires: 15x Wood, 5x Iron, 5x Copper, 35x Nails", icon="horse_rear_up", craft = {{"horseenclosure02", 1}}, need = {{"wood", 15}, {"iron", 5}, {"copper", 5}, {"nails", 35}}, worktime = 5},
                {label = "Horse Enclosure Large", description = "Requires: 15x Wood, 5x Iron, 5x Copper, 35x Nails", icon="horse_rear_up", craft = {{"horseenclosure03", 1}}, need = {{"wood", 15}, {"iron", 5}, {"copper", 5}, {"nails", 35}}, worktime = 5},
                {label = "Horse Enclosure Extra Large", description = "Requires: 15x Wood, 5x Iron, 5x Copper, 35x Nails", icon="horse_rear_up", craft = {{"horseenclosure04", 1}}, need = {{"wood", 15}, {"iron", 5}, {"copper", 5}, {"nails", 35}}, worktime = 5},
                {label = "Torch", description = "Requires: 15x Wood, 5x Iron, 5x Copper, 35x Nails", icon="saddle_lanterns", craft = {{"torch01", 1}}, need = {{"wood", 15}, {"iron", 5}, {"copper", 5}, {"nails", 35}}, worktime = 5},
                {label = "Game Pole Lantern", description = "Requires: 15x Wood, 5x Iron, 5x Copper, 35x Nails", icon="sirevlc_rug", craft = {{"lantern01", 1}}, need = {{"wood", 15}, {"iron", 5}, {"copper", 5}, {"nails", 35}}, worktime = 5},
                {label = "Lamp Post", description = "Requires: 15x Wood, 5x Iron, 5x Copper, 35x Nails", icon="saddle_lanterns", craft = {{"lantern02", 1}}, need = {{"wood", 15}, {"iron", 5}, {"copper", 5}, {"nails", 35}}, worktime = 5},
                {label = "Savage Chair", description = "Requires: 15x Wood, 5x Iron, 5x Copper, 35x Nails", icon="sirevlc_rug", craft = {{"chairsavage", 1}}, need = {{"wood", 15}, {"iron", 5}, {"copper", 5}, {"nails", 35}}, worktime = 5},
                {label = "Sacrifice Table", description = "Requires: 15x Wood, 5x Iron, 5x Copper, 35x Nails", icon="sirevlc_rug", craft = {{"sacrifice", 1}}, need = {{"wood", 15}, {"iron", 5}, {"copper", 5}, {"nails", 35}}, worktime = 5},
                {label = "Survival Decoration", description = "Requires: 15x Wood, 5x Iron, 5x Copper, 35x Nails", icon="sirevlc_rug", craft = {{"decorsurvival", 1}}, need = {{"wood", 15}, {"iron", 5}, {"copper", 5}, {"nails", 35}}, worktime = 5},
                {label = "Clothes Line", description = "Requires: 15x Wood, 5x Iron, 5x Copper, 35x Nails", icon="sirevlc_rug", craft = {{"clothesline", 1}}, need = {{"wood", 15}, {"iron", 5}, {"copper", 5}, {"nails", 35}}, worktime = 5},
                {label = "Native Decoration", description = "Requires: 15x Wood, 5x Iron, 5x Copper, 35x Nails", icon="sirevlc_rug", craft = {{"nativedecor", 1}}, need = {{"wood", 15}, {"iron", 5}, {"copper", 5}, {"nails", 35}}, worktime = 5},
                {label = "Umbrella", description = "Requires: 15x Wood, 5x Iron, 5x Copper, 35x Nails", icon="sirevlc_rug", craft = {{"umbrella", 1}}, need = {{"wood", 15}, {"iron", 5}, {"copper", 5}, {"nails", 35}}, worktime = 5},
            }
        },
        [4] = {
            type = "craft",
            header = "Essentials",
            subheader = "Essentials Items",
            icon = "sirevlc_hitchpost",
            anim = {"amb_work@world_human_hammer@table@male_a@trans", "base_trans_base"},
            recipe = {
                {label = "Stew Pot", description = "Requires: 15x Wood, 15x Iron, 25x Copper, 35x Nails", icon= "upgrade_camp_stew_pot", craft = {{"stewpot", 1}}, need = {{"wood", 15}, {"iron", 15}, {"copper", 25}, {"nails", 35}}, worktime = 5},
                {label = "Chest", description = "Requires: 55x Wood, 25x Iron, 35x Copper, 135x Nails", icon="horse_blankets", craft = {{"campchest", 1}}, need = {{"wood", 55}, {"iron", 25}, {"copper", 35}, {"nails", 135}}, worktime = 5},
                {label = "Butcher Table", description = "Requires: 15x Wood, 5x Iron, 5x Copper, 35x Nails", icon="provision_goat_hair", craft = {{"butchertable", 1}}, need = {{"wood", 15}, {"iron", 5}, {"copper", 5}, {"nails", 35}}, worktime = 5},
            }
        },
    }
}