Config.Workbenches = {
    [1] = {
        ["Cover"] = "coverbook",
        ["Name"] = "Bancada de teste",
        ["Coords"] = {
            -2392.17,
            -2375.76,
            60.17,
            150,
        },
        ["Distance"] = 2,
        ["DrawTxt"] = 0,
        ["SpawnProp"] = "p_workbench01x",
        ["Animation"] = {
            "amb_work@world_human_write_notebook@male_a@idle_a",
            "idle_a",
        },
        ["UseBlip"] = "false",
        ["Receipes"] = {
            "adrenalina",
            "adrenalinaoficial",
            "alcohol_beer_glass",
            "alcohol_beer_pint",
            "antibiotico",
            "antidoto",
            "antiveneno",
            "atadura",
            "axe",
            "bandagem",
            "bottle_pack",
            "chef_tomato_sauce",
            "coador",
            "consumable_chickenpie",
            "consumable_coffeecake",
            "copperbar",
            "cotton_line",
            "empty_crate",
            "epinefrina",
            "fishnchips",
            "french_fries",
            "fried_bluegill",
            "glue",
            "goldbar",
            "goldplate",
            "iced_coffee_sugar",
            "iced_tea_green",
            "iced_tea_lemon",
            "iced_tea_peach",
            "ironbar",
            "ironhammer",
            "juice_apple",
            "juice_cherry",
            "juice_orange",
            "label",
            "leather_handle",
            "lemonade_blueberry",
            "lemonade_raspberry",
            "lemonade_strawberry",
            "meat_tender_pork_cooked",
            "milkshake_blueberry",
            "milkshake_chocolate",
            "milkshake_chocolate_mint",
            "milkshake_strawberry",
            "mochila10",
            "mochila15",
            "mochila5",
            "mochila50",
            "muffin_berry",
            "nails",
            "paint",
            "pickaxe",
            "pistolmold",
            "plastic_capsule",
            "platinum_bar",
            "polpa_amora",
            "polpa_banana",
            "polpa_framboesa",
            "polpa_groselha_preta",
            "polpa_laranja",
            "polpa_limao",
            "polpa_maca",
            "polpa_mirtilo",
            "polpa_morango",
            "polpa_pessego",
            "polpa_uva",
            "purse4",
            "repeatermold",
            "revolvercylmold",
            "rice_cooked",
            "riflemold",
            "s_wooden_box",
            "sacoplastico",
            "sactravail",
            "Seta_de_Pedra",
            "steel_bar",
            "tonico",
            "tonicopotente",
            "tool_chisel",
            "tool_handle1",
            "tool_handle2",
            "tool_handle3",
            "tool_handle4",
            "tool_heavy_pickaxe",
            "tool_woodplaner",
            "tool_woodsaw",
            "varnish",
            "weapon_fishingrod",
            "weapon_kit_camera",
            "WEAPON_MELEE_KNIFE",
            "WEAPON_MELEE_LANTERN",
            "weaponpart",
            "weaponpart_cylinder",
            "weaponpart_hammer",
            "weaponpart_spring",
            "weaponpart_trigger",
            "weaponpart2",
            "wooden_crate",
        },
        ["Jobs"] = {
        },
        ["JobsGrades"] = {
        },
    },
    [2] = {
        ["Cover"] = "medicos",
        ["Name"] = "Bancada Médica",
        ["Coords"] = {
            -5501.52,
            -2964.94,
            -0.713,
            150,
        },
        ["Distance"] = 2,
        ["DrawTxt"] = "Bancada Médica",
        ["SpawnProp"] = "false",
        ["Animation"] = {
            "amb_work@world_human_write_notebook@male_a@idle_a",
            "idle_a",
        },
        ["UseBlip"] = "false",
        ["Receipes"] = {
            "adrenalina",
            "adrenalinaoficial",
            "antibiotico",
            "antidoto",
            "antiveneno",
            "atadura",
            "bandagem",
            "epinefrina",
            "tonico",
            "tonicopotente",
        },
        ["Jobs"] = {
            "medicoam",
            "medicobw",
            "medicorh",
            "medicosd",
            "medicostb",
            "medicotw",
            "medicovl",
        },
        ["JobsGrades"] = {
        },
    },
    [3] = {
        ["Cover"] = "medicos",
        ["Name"] = "Bancada Médica",
        ["Coords"] = {
            -3732.92,
            -2635,
            -13.32,
        },
        ["Distance"] = 2,
        ["DrawTxt"] = "Bancada Médica",
        ["SpawnProp"] = "false",
        ["Animation"] = {
            "amb_work@world_human_write_notebook@male_a@idle_a",
            "idle_a",
        },
        ["UseBlip"] = "false",
        ["Receipes"] = {
            "adrenalina",
            "adrenalinaoficial",
            "antibiotico",
            "antidoto",
            "antiveneno",
            "atadura",
            "bandagem",
            "epinefrina",
            "tonico",
            "tonicopotente",
        },
        ["Jobs"] = {
            "medicoam",
            "medicobw",
            "medicorh",
            "medicosd",
            "medicostb",
            "medicotw",
            "medicovl",
        },
        ["JobsGrades"] = {
        },
    },
    [4] = {
        ["Cover"] = "medicos",
        ["Name"] = "Bancada Médica",
        ["Coords"] = {
            -787.617,
            -1302.67,
            43.791,
        },
        ["Distance"] = 2,
        ["DrawTxt"] = "Bancada Médica",
        ["SpawnProp"] = "false",
        ["Animation"] = {
            "amb_work@world_human_write_notebook@male_a@idle_a",
            "idle_a",
        },
        ["UseBlip"] = "false",
        ["Receipes"] = {
            "adrenalina",
            "adrenalinaoficial",
            "antibiotico",
            "antidoto",
            "antiveneno",
            "atadura",
            "bandagem",
            "epinefrina",
            "tonico",
            "tonicopotente",
        },
        ["Jobs"] = {
            "medicoam",
            "medicobw",
            "medicorh",
            "medicosd",
            "medicostb",
            "medicotw",
            "medicovl",
        },
        ["JobsGrades"] = {
        },
    },
    [5] = {
        ["Cover"] = "medicos",
        ["Name"] = "Bancada Médica",
        ["Coords"] = {
            -1805.99,
            -432.491,
            158.84,
        },
        ["Distance"] = 2,
        ["DrawTxt"] = "Bancada Médica",
        ["SpawnProp"] = "false",
        ["Animation"] = {
            "amb_work@world_human_write_notebook@male_a@idle_a",
            "idle_a",
        },
        ["UseBlip"] = "false",
        ["Receipes"] = {
            "adrenalina",
            "adrenalinaoficial",
            "antibiotico",
            "antidoto",
            "antiveneno",
            "atadura",
            "bandagem",
            "epinefrina",
            "tonico",
            "tonicopotente",
        },
        ["Jobs"] = {
            "medicoam",
            "medicobw",
            "medicorh",
            "medicosd",
            "medicostb",
            "medicotw",
            "medicovl",
        },
        ["JobsGrades"] = {
        },
    },
    [6] = {
        ["Cover"] = "medicos",
        ["Name"] = "Bancada Médica",
        ["Coords"] = {
            -287.785,
            811.405,
            119.38,
        },
        ["Distance"] = 2,
        ["DrawTxt"] = "Bancada Médica",
        ["SpawnProp"] = "false",
        ["Animation"] = {
            "amb_work@world_human_write_notebook@male_a@idle_a",
            "idle_a",
        },
        ["UseBlip"] = "false",
        ["Receipes"] = {
            "adrenalina",
            "adrenalinaoficial",
            "antibiotico",
            "antidoto",
            "antiveneno",
            "atadura",
            "bandagem",
            "epinefrina",
            "tonico",
            "tonicopotente",
        },
        ["Jobs"] = {
            "medicoam",
            "medicobw",
            "medicorh",
            "medicosd",
            "medicostb",
            "medicotw",
            "medicovl",
        },
        ["JobsGrades"] = {
        },
    },
    [7] = {
        ["Cover"] = "medicos",
        ["Name"] = "Bancada Médica",
        ["Coords"] = {
            1372.27,
            -1305.6,
            77.971,
        },
        ["Distance"] = 2,
        ["DrawTxt"] = "Bancada Médica",
        ["SpawnProp"] = "false",
        ["Animation"] = {
            "amb_work@world_human_write_notebook@male_a@idle_a",
            "idle_a",
        },
        ["UseBlip"] = "false",
        ["Receipes"] = {
            "adrenalina",
            "adrenalinaoficial",
            "antibiotico",
            "antidoto",
            "antiveneno",
            "atadura",
            "bandagem",
            "epinefrina",
            "tonico",
            "tonicopotente",
        },
        ["Jobs"] = {
            "medicoam",
            "medicobw",
            "medicorh",
            "medicosd",
            "medicostb",
            "medicotw",
            "medicovl",
        },
        ["JobsGrades"] = {
        },
    },
    [8] = {
        ["Cover"] = "medicos",
        ["Name"] = "Bancada Médica",
        ["Coords"] = {
            2730.52,
            -1229.1,
            50.37,
        },
        ["Distance"] = 2,
        ["DrawTxt"] = "Bancada Médica",
        ["SpawnProp"] = "false",
        ["Animation"] = {
            "amb_work@world_human_write_notebook@male_a@idle_a",
            "idle_a",
        },
        ["UseBlip"] = "false",
        ["Receipes"] = {
            "adrenalina",
            "adrenalinaoficial",
            "antibiotico",
            "antidoto",
            "antiveneno",
            "atadura",
            "bandagem",
            "epinefrina",
            "tonico",
            "tonicopotente",
        },
        ["Jobs"] = {
            "medicoam",
            "medicobw",
            "medicorh",
            "medicosd",
            "medicostb",
            "medicotw",
            "medicovl",
        },
        ["JobsGrades"] = {
        },
    },
    [9] = {
        ["Cover"] = "artesanato",
        ["Name"] = "Bancada Artesão",
        ["Coords"] = {
            -5203.82,
            -3493.32,
            -21.7,
        },
        ["Distance"] = 2,
        ["DrawTxt"] = "Bancada Artesão",
        ["SpawnProp"] = "false",
        ["Animation"] = {
            "amb_work@world_human_write_notebook@male_a@idle_a",
            "idle_a",
        },
        ["UseBlip"] = "false",
        ["Receipes"] = {
            "bottle_pack",
            "coador",
            "cotton_line",
            "empty_crate",
            "glue",
            "label",
            "leather_handle",
            "mochila10",
            "mochila15",
            "mochila5",
            "mochila50",
            "paint",
            "pistolmold",
            "plastic_capsule",
            "purse4",
            "repeatermold",
            "revolvercylmold",
            "riflemold",
            "s_wooden_box",
            "sacoplastico",
            "sactravail",
            "tool_handle1",
            "tool_handle2",
            "tool_handle3",
            "tool_handle4",
            "varnish",
            "weapon_fishingrod",
            "weapon_kit_camera",
            "wooden_crate",
        },
        ["Jobs"] = {
            "artesaotw",
        },
        ["JobsGrades"] = {
        },
    },
    [10] = {
        ["Cover"] = "artesanato",
        ["Name"] = "Bancada Artesão",
        ["Coords"] = {
            -2396.48,
            -2378.11,
            61.254,
        },
        ["Distance"] = 2,
        ["DrawTxt"] = "Bancada Artesão",
        ["SpawnProp"] = "false",
        ["Animation"] = {
            "amb_work@world_human_write_notebook@male_a@idle_a",
            "idle_a",
        },
        ["UseBlip"] = "false",
        ["Receipes"] = {
            "bottle_pack",
            "coador",
            "cotton_line",
            "empty_crate",
            "glue",
            "label",
            "leather_handle",
            "mochila10",
            "mochila15",
            "mochila5",
            "mochila50",
            "paint",
            "pistolmold",
            "plastic_capsule",
            "purse4",
            "repeatermold",
            "revolvercylmold",
            "riflemold",
            "s_wooden_box",
            "sacoplastico",
            "sactravail",
            "tool_handle1",
            "tool_handle2",
            "tool_handle3",
            "tool_handle4",
            "varnish",
            "weapon_fishingrod",
            "weapon_kit_camera",
            "wooden_crate",
        },
        ["Jobs"] = {
            "artesaomac",
        },
        ["JobsGrades"] = {
        },
    },
    [11] = {
        ["Cover"] = "artesanato",
        ["Name"] = "Bancada Artesão",
        ["Coords"] = {
            -782.249,
            -1384.45,
            44.273,
        },
        ["Distance"] = 2,
        ["DrawTxt"] = "Bancada Artesão",
        ["SpawnProp"] = "false",
        ["Animation"] = {
            "amb_work@world_human_write_notebook@male_a@idle_a",
            "idle_a",
        },
        ["UseBlip"] = "false",
        ["Receipes"] = {
            "bottle_pack",
            "coador",
            "cotton_line",
            "empty_crate",
            "glue",
            "label",
            "leather_handle",
            "mochila10",
            "mochila15",
            "mochila5",
            "mochila50",
            "paint",
            "pistolmold",
            "plastic_capsule",
            "purse4",
            "repeatermold",
            "revolvercylmold",
            "riflemold",
            "s_wooden_box",
            "sacoplastico",
            "sactravail",
            "tool_handle1",
            "tool_handle2",
            "tool_handle3",
            "tool_handle4",
            "varnish",
            "weapon_fishingrod",
            "weapon_kit_camera",
            "wooden_crate",
        },
        ["Jobs"] = {
            "artesaobw",
        },
        ["JobsGrades"] = {
        },
    },
    [12] = {
        ["Cover"] = "artesanato",
        ["Name"] = "Bancada Artesão",
        ["Coords"] = {
            -1767.97,
            -431.378,
            155.27,
        },
        ["Distance"] = 2,
        ["DrawTxt"] = "Bancada Artesão",
        ["SpawnProp"] = "false",
        ["Animation"] = {
            "amb_work@world_human_write_notebook@male_a@idle_a",
            "idle_a",
        },
        ["UseBlip"] = "false",
        ["Receipes"] = {
            "bottle_pack",
            "coador",
            "cotton_line",
            "empty_crate",
            "glue",
            "label",
            "leather_handle",
            "mochila10",
            "mochila15",
            "mochila5",
            "mochila50",
            "paint",
            "pistolmold",
            "plastic_capsule",
            "purse4",
            "repeatermold",
            "revolvercylmold",
            "riflemold",
            "s_wooden_box",
            "sacoplastico",
            "sactravail",
            "tool_handle1",
            "tool_handle2",
            "tool_handle3",
            "tool_handle4",
            "varnish",
            "weapon_fishingrod",
            "weapon_kit_camera",
            "wooden_crate",
        },
        ["Jobs"] = {
            "artesaost",
        },
        ["JobsGrades"] = {
        },
    },
    [13] = {
        ["Cover"] = "artesanato",
        ["Name"] = "Bancada Artesão",
        ["Coords"] = {
            -369.502,
            796.237,
            116.19,
        },
        ["Distance"] = 2,
        ["DrawTxt"] = "Bancada Artesão",
        ["SpawnProp"] = "false",
        ["Animation"] = {
            "amb_work@world_human_write_notebook@male_a@idle_a",
            "idle_a",
        },
        ["UseBlip"] = "false",
        ["Receipes"] = {
            "bottle_pack",
            "coador",
            "cotton_line",
            "empty_crate",
            "glue",
            "label",
            "leather_handle",
            "mochila10",
            "mochila15",
            "mochila5",
            "mochila50",
            "paint",
            "pistolmold",
            "plastic_capsule",
            "purse4",
            "repeatermold",
            "revolvercylmold",
            "riflemold",
            "s_wooden_box",
            "sacoplastico",
            "sactravail",
            "tool_handle1",
            "tool_handle2",
            "tool_handle3",
            "tool_handle4",
            "varnish",
            "weapon_fishingrod",
            "weapon_kit_camera",
            "wooden_crate",
        },
        ["Jobs"] = {
            "artesaovl",
        },
        ["JobsGrades"] = {
        },
    },
    [14] = {
        ["Cover"] = "artesanato",
        ["Name"] = "Bancada Artesão",
        ["Coords"] = {
            1447.71,
            -1393.86,
            79.48,
        },
        ["Distance"] = 2,
        ["DrawTxt"] = "Bancada Artesão",
        ["SpawnProp"] = "false",
        ["Animation"] = {
            "amb_work@world_human_write_notebook@male_a@idle_a",
            "idle_a",
        },
        ["UseBlip"] = "false",
        ["Receipes"] = {
            "bottle_pack",
            "coador",
            "cotton_line",
            "empty_crate",
            "glue",
            "label",
            "leather_handle",
            "mochila10",
            "mochila15",
            "mochila5",
            "mochila50",
            "paint",
            "pistolmold",
            "plastic_capsule",
            "purse4",
            "repeatermold",
            "revolvercylmold",
            "riflemold",
            "s_wooden_box",
            "sacoplastico",
            "sactravail",
            "tool_handle1",
            "tool_handle2",
            "tool_handle3",
            "tool_handle4",
            "varnish",
            "weapon_fishingrod",
            "weapon_kit_camera",
            "wooden_crate",
        },
        ["Jobs"] = {
            "artesaorh",
        },
        ["JobsGrades"] = {
        },
    },
    [15] = {
        ["Cover"] = "artesanato",
        ["Name"] = "Bancada Artesão",
        ["Coords"] = {
            2834.98,
            -1307.61,
            46.74,
        },
        ["Distance"] = 2,
        ["DrawTxt"] = "Bancada Artesão",
        ["SpawnProp"] = "false",
        ["Animation"] = {
            "amb_work@world_human_write_notebook@male_a@idle_a",
            "idle_a",
        },
        ["UseBlip"] = "false",
        ["Receipes"] = {
            "bottle_pack",
            "coador",
            "cotton_line",
            "empty_crate",
            "glue",
            "label",
            "leather_handle",
            "mochila10",
            "mochila15",
            "mochila5",
            "mochila50",
            "paint",
            "pistolmold",
            "plastic_capsule",
            "purse4",
            "repeatermold",
            "revolvercylmold",
            "riflemold",
            "s_wooden_box",
            "sacoplastico",
            "sactravail",
            "tool_handle1",
            "tool_handle2",
            "tool_handle3",
            "tool_handle4",
            "varnish",
            "weapon_fishingrod",
            "weapon_kit_camera",
            "wooden_crate",
        },
        ["Jobs"] = {
            "artesaosd",
        },
        ["JobsGrades"] = {
        },
    },
    [16] = {
        ["Cover"] = "doceria",
        ["Name"] = "Bancada Doceria",
        ["Coords"] = {
            -789.443,
            -1378.23,
            43.975,
        },
        ["Distance"] = 2,
        ["DrawTxt"] = "Bancada Doceria",
        ["SpawnProp"] = "false",
        ["Animation"] = {
            "amb_work@world_human_write_notebook@male_a@idle_a",
            "idle_a",
        },
        ["UseBlip"] = "false",
        ["Receipes"] = {
            "consumable_coffeecake",
            "iced_tea_green",
            "iced_tea_lemon",
            "iced_tea_peach",
            "milkshake_blueberry",
            "milkshake_chocolate",
            "milkshake_chocolate_mint",
            "milkshake_strawberry",
            "muffin_berry",
            "polpa_amora",
            "polpa_banana",
            "polpa_framboesa",
            "polpa_groselha_preta",
            "polpa_laranja",
            "polpa_limao",
            "polpa_maca",
            "polpa_mirtilo",
            "polpa_morango",
            "polpa_pessego",
            "polpa_uva",
        },
        ["Jobs"] = {
            "doceriabw",
        },
        ["JobsGrades"] = {
        },
    },
    [17] = {
        ["Cover"] = "doceria",
        ["Name"] = "Bancada Doceria",
        ["Coords"] = {
            -1720.6,
            -434.03,
            152.2,
        },
        ["Distance"] = 2,
        ["DrawTxt"] = "Bancada Doceria",
        ["SpawnProp"] = "false",
        ["Animation"] = {
            "amb_work@world_human_write_notebook@male_a@idle_a",
            "idle_a",
        },
        ["UseBlip"] = "false",
        ["Receipes"] = {
            "consumable_coffeecake",
            "iced_tea_green",
            "iced_tea_lemon",
            "iced_tea_peach",
            "milkshake_blueberry",
            "milkshake_chocolate",
            "milkshake_chocolate_mint",
            "milkshake_strawberry",
            "muffin_berry",
            "polpa_amora",
            "polpa_banana",
            "polpa_framboesa",
            "polpa_groselha_preta",
            "polpa_laranja",
            "polpa_limao",
            "polpa_maca",
            "polpa_mirtilo",
            "polpa_morango",
            "polpa_pessego",
            "polpa_uva",
        },
        ["Jobs"] = {
            "doceriastb",
        },
        ["JobsGrades"] = {
        },
    },
    [18] = {
        ["Cover"] = "doceria",
        ["Name"] = "Bancada Doceria",
        ["Coords"] = {
            1437.96,
            -1405.42,
            80.074,
        },
        ["Distance"] = 2,
        ["DrawTxt"] = "Bancada Doceria",
        ["SpawnProp"] = "false",
        ["Animation"] = {
            "amb_work@world_human_write_notebook@male_a@idle_a",
            "idle_a",
        },
        ["UseBlip"] = "false",
        ["Receipes"] = {
            "consumable_coffeecake",
            "iced_tea_green",
            "iced_tea_lemon",
            "iced_tea_peach",
            "milkshake_blueberry",
            "milkshake_chocolate",
            "milkshake_chocolate_mint",
            "milkshake_strawberry",
            "muffin_berry",
            "polpa_amora",
            "polpa_banana",
            "polpa_framboesa",
            "polpa_groselha_preta",
            "polpa_laranja",
            "polpa_limao",
            "polpa_maca",
            "polpa_mirtilo",
            "polpa_morango",
            "polpa_pessego",
            "polpa_uva",
        },
        ["Jobs"] = {
            "doceriarh",
        },
        ["JobsGrades"] = {
        },
    },
    [19] = {
        ["Cover"] = "ferraria",
        ["Name"] = "Bancada Ferraria",
        ["Coords"] = {
            1446.45,
            -1453.8,
            77.867,
        },
        ["Distance"] = 2,
        ["DrawTxt"] = "Bancada Ferraria",
        ["SpawnProp"] = "false",
        ["Animation"] = {
            "amb_work@world_human_write_notebook@male_a@idle_a",
            "idle_a",
        },
        ["UseBlip"] = "false",
        ["Receipes"] = {
            "axe",
            "copperbar",
            "goldbar",
            "goldplate",
            "ironbar",
            "nails",
            "pickaxe",
            "platinum_bar",
            "steel_bar",
            "tool_chisel",
            "tool_heavy_pickaxe",
            "tool_woodplaner",
            "tool_woodsaw",
            "WEAPON_MELEE_KNIFE",
            "weaponpart",
            "weaponpart_cylinder",
            "weaponpart_hammer",
            "weaponpart_spring",
            "weaponpart_trigger",
            "weaponpart2",
        },
        ["Jobs"] = {
            "ferreirorh",
        },
        ["JobsGrades"] = {
        },
    },
    [20] = {
        ["Cover"] = "ferraria",
        ["Name"] = "Bancada Ferraria",
        ["Coords"] = {
            1415,
            279.191,
            89.486,
        },
        ["Distance"] = 2,
        ["DrawTxt"] = "Bancada Ferraria",
        ["SpawnProp"] = "false",
        ["Animation"] = {
            "amb_work@world_human_write_notebook@male_a@idle_a",
            "idle_a",
        },
        ["UseBlip"] = "false",
        ["Receipes"] = {
            "axe",
            "copperbar",
            "goldbar",
            "goldplate",
            "ironbar",
            "nails",
            "pickaxe",
            "platinum_bar",
            "steel_bar",
            "tool_chisel",
            "tool_heavy_pickaxe",
            "tool_woodplaner",
            "tool_woodsaw",
            "WEAPON_MELEE_KNIFE",
            "weaponpart",
            "weaponpart_cylinder",
            "weaponpart_hammer",
            "weaponpart_spring",
            "weaponpart_trigger",
            "weaponpart2",
        },
        ["Jobs"] = {
            "ferreiroer",
        },
        ["JobsGrades"] = {
        },
    },
    [21] = {
        ["Cover"] = "ferraria",
        ["Name"] = "Bancada Ferraria",
        ["Coords"] = {
            2602.01,
            -929.098,
            42.119,
        },
        ["Distance"] = 2,
        ["DrawTxt"] = "Bancada Ferraria",
        ["SpawnProp"] = "false",
        ["Animation"] = {
            "amb_work@world_human_write_notebook@male_a@idle_a",
            "idle_a",
        },
        ["UseBlip"] = "false",
        ["Receipes"] = {
            "axe",
            "copperbar",
            "goldbar",
            "goldplate",
            "ironbar",
            "nails",
            "pickaxe",
            "platinum_bar",
            "steel_bar",
            "tool_chisel",
            "tool_heavy_pickaxe",
            "tool_woodplaner",
            "tool_woodsaw",
            "WEAPON_MELEE_KNIFE",
            "weaponpart",
            "weaponpart_cylinder",
            "weaponpart_hammer",
            "weaponpart_spring",
            "weaponpart_trigger",
            "weaponpart2",
        },
        ["Jobs"] = {
            "ferreirosd",
        },
        ["JobsGrades"] = {
        },
    },
    [22] = {
        ["Cover"] = "ferraria",
        ["Name"] = "Bancada Ferraria",
        ["Coords"] = {
            -270.858,
            771.89,
            118.59,
        },
        ["Distance"] = 2,
        ["DrawTxt"] = "Bancada Ferraria",
        ["SpawnProp"] = "false",
        ["Animation"] = {
            "amb_work@world_human_write_notebook@male_a@idle_a",
            "idle_a",
        },
        ["UseBlip"] = "false",
        ["Receipes"] = {
            "axe",
            "copperbar",
            "goldbar",
            "goldplate",
            "ironbar",
            "nails",
            "pickaxe",
            "platinum_bar",
            "steel_bar",
            "tool_chisel",
            "tool_heavy_pickaxe",
            "tool_woodplaner",
            "tool_woodsaw",
            "WEAPON_MELEE_KNIFE",
            "weaponpart",
            "weaponpart_cylinder",
            "weaponpart_hammer",
            "weaponpart_spring",
            "weaponpart_trigger",
            "weaponpart2",
        },
        ["Jobs"] = {
            "ferreirovl",
        },
        ["JobsGrades"] = {
        },
    },
    [23] = {
        ["Cover"] = "ferraria",
        ["Name"] = "Bancada Ferraria",
        ["Coords"] = {
            -863.527,
            -1390.21,
            43.593,
        },
        ["Distance"] = 2,
        ["DrawTxt"] = "Bancada Ferraria",
        ["SpawnProp"] = "false",
        ["Animation"] = {
            "amb_work@world_human_write_notebook@male_a@idle_a",
            "idle_a",
        },
        ["UseBlip"] = "false",
        ["Receipes"] = {
            "axe",
            "copperbar",
            "goldbar",
            "goldplate",
            "ironbar",
            "nails",
            "pickaxe",
            "platinum_bar",
            "steel_bar",
            "tool_chisel",
            "tool_heavy_pickaxe",
            "tool_woodplaner",
            "tool_woodsaw",
            "WEAPON_MELEE_KNIFE",
            "weaponpart",
            "weaponpart_cylinder",
            "weaponpart_hammer",
            "weaponpart_spring",
            "weaponpart_trigger",
            "weaponpart2",
        },
        ["Jobs"] = {
            "ferreirobw",
        },
        ["JobsGrades"] = {
        },
    },
    [24] = {
        ["Cover"] = "ferraria",
        ["Name"] = "Bancada Ferraria",
        ["Coords"] = {
            -3681.25,
            -2565.76,
            -13.55,
        },
        ["Distance"] = 2,
        ["DrawTxt"] = "Bancada Ferraria",
        ["SpawnProp"] = "false",
        ["Animation"] = {
            "amb_work@world_human_write_notebook@male_a@idle_a",
            "idle_a",
        },
        ["UseBlip"] = "false",
        ["Receipes"] = {
            "axe",
            "copperbar",
            "goldbar",
            "goldplate",
            "ironbar",
            "nails",
            "pickaxe",
            "platinum_bar",
            "steel_bar",
            "tool_chisel",
            "tool_heavy_pickaxe",
            "tool_woodplaner",
            "tool_woodsaw",
            "WEAPON_MELEE_KNIFE",
            "weaponpart",
            "weaponpart_cylinder",
            "weaponpart_hammer",
            "weaponpart_spring",
            "weaponpart_trigger",
            "weaponpart2",
        },
        ["Jobs"] = {
            "ferreiroam",
        },
        ["JobsGrades"] = {
        },
    },
    [25] = {
        ["Cover"] = "saloon",
        ["Name"] = "Bancada Saloon",
        ["Coords"] = {
            -5518.86,
            -2905.79,
            -1.751,
        },
        ["Distance"] = 2,
        ["DrawTxt"] = "Bancada Saloon",
        ["SpawnProp"] = "false",
        ["Animation"] = {
            "amb_work@world_human_write_notebook@male_a@idle_a",
            "idle_a",
        },
        ["UseBlip"] = "false",
        ["Receipes"] = {
            "alcohol_beer_glass",
            "alcohol_beer_pint",
            "chef_tomato_sauce",
            "consumable_chickenpie",
            "fishnchips",
            "french_fries",
            "fried_bluegill",
            "iced_coffee_sugar",
            "juice_apple",
            "juice_cherry",
            "juice_orange",
            "lemonade_blueberry",
            "lemonade_raspberry",
            "lemonade_strawberry",
            "meat_tender_pork_cooked",
            "rice_cooked",
        },
        ["Jobs"] = {
            "saloontw",
        },
        ["JobsGrades"] = {
        },
    },
    [26] = {
        ["Cover"] = "saloon",
        ["Name"] = "Bancada Saloon",
        ["Coords"] = {
            -3698.07,
            -2601.3,
            -13.31,
        },
        ["Distance"] = 2,
        ["DrawTxt"] = "Bancada Saloon",
        ["SpawnProp"] = "false",
        ["Animation"] = {
            "amb_work@world_human_write_notebook@male_a@idle_a",
            "idle_a",
        },
        ["UseBlip"] = "false",
        ["Receipes"] = {
            "alcohol_beer_glass",
            "alcohol_beer_pint",
            "chef_tomato_sauce",
            "consumable_chickenpie",
            "fishnchips",
            "french_fries",
            "fried_bluegill",
            "iced_coffee_sugar",
            "juice_apple",
            "juice_cherry",
            "juice_orange",
            "lemonade_blueberry",
            "lemonade_raspberry",
            "lemonade_strawberry",
            "meat_tender_pork_cooked",
            "rice_cooked",
        },
        ["Jobs"] = {
            "saloonam",
        },
        ["JobsGrades"] = {
        },
    },
    [27] = {
        ["Cover"] = "saloon",
        ["Name"] = "Bancada Saloon",
        ["Coords"] = {
            -819.341,
            -1319.49,
            43.678,
        },
        ["Distance"] = 2,
        ["DrawTxt"] = "Bancada Saloon",
        ["SpawnProp"] = "false",
        ["Animation"] = {
            "amb_work@world_human_write_notebook@male_a@idle_a",
            "idle_a",
        },
        ["UseBlip"] = "false",
        ["Receipes"] = {
            "alcohol_beer_glass",
            "alcohol_beer_pint",
            "chef_tomato_sauce",
            "consumable_chickenpie",
            "fishnchips",
            "french_fries",
            "fried_bluegill",
            "iced_coffee_sugar",
            "juice_apple",
            "juice_cherry",
            "juice_orange",
            "lemonade_blueberry",
            "lemonade_raspberry",
            "lemonade_strawberry",
            "meat_tender_pork_cooked",
            "rice_cooked",
        },
        ["Jobs"] = {
            "saloonbw",
        },
        ["JobsGrades"] = {
        },
    },
    [28] = {
        ["Cover"] = "saloon",
        ["Name"] = "Bancada Saloon",
        ["Coords"] = {
            -313.667,
            806.102,
            118.98,
        },
        ["Distance"] = 2,
        ["DrawTxt"] = "Bancada Saloon",
        ["SpawnProp"] = "false",
        ["Animation"] = {
            "amb_work@world_human_write_notebook@male_a@idle_a",
            "idle_a",
        },
        ["UseBlip"] = "false",
        ["Receipes"] = {
            "alcohol_beer_glass",
            "alcohol_beer_pint",
            "chef_tomato_sauce",
            "consumable_chickenpie",
            "fishnchips",
            "french_fries",
            "fried_bluegill",
            "iced_coffee_sugar",
            "juice_apple",
            "juice_cherry",
            "juice_orange",
            "lemonade_blueberry",
            "lemonade_raspberry",
            "lemonade_strawberry",
            "meat_tender_pork_cooked",
            "rice_cooked",
        },
        ["Jobs"] = {
            "saloonvl",
        },
        ["JobsGrades"] = {
        },
    },
    [29] = {
        ["Cover"] = "saloon",
        ["Name"] = "Bancada Saloon",
        ["Coords"] = {
            1339.2,
            -1374.39,
            80.48,
        },
        ["Distance"] = 2,
        ["DrawTxt"] = "Bancada Saloon",
        ["SpawnProp"] = "false",
        ["Animation"] = {
            "amb_work@world_human_write_notebook@male_a@idle_a",
            "idle_a",
        },
        ["UseBlip"] = "false",
        ["Receipes"] = {
            "alcohol_beer_glass",
            "alcohol_beer_pint",
            "chef_tomato_sauce",
            "consumable_chickenpie",
            "fishnchips",
            "french_fries",
            "fried_bluegill",
            "iced_coffee_sugar",
            "juice_apple",
            "juice_cherry",
            "juice_orange",
            "lemonade_blueberry",
            "lemonade_raspberry",
            "lemonade_strawberry",
            "meat_tender_pork_cooked",
            "rice_cooked",
        },
        ["Jobs"] = {
            "saloonrh",
        },
        ["JobsGrades"] = {
        },
    },
    [30] = {
        ["Cover"] = "saloon",
        ["Name"] = "Bancada Saloon",
        ["Coords"] = {
            2640.29,
            -1222.76,
            53.38,
        },
        ["Distance"] = 2,
        ["DrawTxt"] = "Bancada Saloon",
        ["SpawnProp"] = "false",
        ["Animation"] = {
            "amb_work@world_human_write_notebook@male_a@idle_a",
            "idle_a",
        },
        ["UseBlip"] = "false",
        ["Receipes"] = {
            "alcohol_beer_glass",
            "alcohol_beer_pint",
            "chef_tomato_sauce",
            "consumable_chickenpie",
            "fishnchips",
            "french_fries",
            "fried_bluegill",
            "iced_coffee_sugar",
            "juice_apple",
            "juice_cherry",
            "juice_orange",
            "lemonade_blueberry",
            "lemonade_raspberry",
            "lemonade_strawberry",
            "meat_tender_pork_cooked",
            "rice_cooked",
        },
        ["Jobs"] = {
            "saloonsd",
        },
        ["JobsGrades"] = {
        },
    },
    [31] = {
        ["Cover"] = "saloon",
        ["Name"] = "Bancada Saloon",
        ["Coords"] = {
            2939.86,
            523.326,
            45.336,
        },
        ["Distance"] = 2,
        ["DrawTxt"] = "Bancada Saloon",
        ["SpawnProp"] = "false",
        ["Animation"] = {
            "amb_work@world_human_write_notebook@male_a@idle_a",
            "idle_a",
        },
        ["UseBlip"] = "false",
        ["Receipes"] = {
            "alcohol_beer_glass",
            "alcohol_beer_pint",
            "chef_tomato_sauce",
            "consumable_chickenpie",
            "fishnchips",
            "french_fries",
            "fried_bluegill",
            "iced_coffee_sugar",
            "juice_apple",
            "juice_cherry",
            "juice_orange",
            "lemonade_blueberry",
            "lemonade_raspberry",
            "lemonade_strawberry",
            "meat_tender_pork_cooked",
            "rice_cooked",
        },
        ["Jobs"] = {
            "saloonvh",
        },
        ["JobsGrades"] = {
        },
    },
    [32] = {
        ["Cover"] = "saloon",
        ["Name"] = "Bancada Saloon",
        ["Coords"] = {
            1445.9,
            376.176,
            89.887,
        },
        ["Distance"] = 2,
        ["DrawTxt"] = "Bancada Saloon",
        ["SpawnProp"] = "false",
        ["Animation"] = {
            "amb_work@world_human_write_notebook@male_a@idle_a",
            "idle_a",
        },
        ["UseBlip"] = "false",
        ["Receipes"] = {
            "alcohol_beer_glass",
            "alcohol_beer_pint",
            "chef_tomato_sauce",
            "consumable_chickenpie",
            "fishnchips",
            "french_fries",
            "fried_bluegill",
            "iced_coffee_sugar",
            "juice_apple",
            "juice_cherry",
            "juice_orange",
            "lemonade_blueberry",
            "lemonade_raspberry",
            "lemonade_strawberry",
            "meat_tender_pork_cooked",
            "rice_cooked",
        },
        ["Jobs"] = {
            "salooner",
        },
        ["JobsGrades"] = {
        },
    },
}
